definition_version: 1
streamlit:
  name: Access Requestor
  query_warehouse: SNOW_WH
  main_file: streamlit_app.py
  env_file: environment.yml
dependencies:
  - python=3.10.*
  - snowflake-snowpark-python
  - streamlit